const CHANGE_BACKGROUND = 'CHANGE_BACKGROUND'
const CHANGE_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT'
const CHANGE_NOTE = 'CHANGE_NOTE'
const ADD_NOTE = 'ADD_NOTE'

export default {
  CHANGE_BACKGROUND,
  CHANGE_SEARCH_TEXT,
  CHANGE_NOTE,
  ADD_NOTE
}
